### ISSUE TITLE
getFeatures function

### ISSUE THREAD

**Issue by MirkoBr** [ZarnackGroup/m6Aboost#1]
The 'getFeatuers' function contains a variable named 'test_gff3' that should be exchanged to "annotation". But I anyhow would suggest to remove the part where the annotation is read from the function and simply expect as input what is needed. I posted the code i mean below:

        anno <- makeTxDbFromGFF(test_gff3, format = "gff3")
        annoInfo <- import.gff3(test_gff3)

        anno_gene <- genes(anno)
        idx <- match(anno_gene$gene_id, annoInfo$gene_id)
        mcols(anno_gene) <- cbind(mcols(anno_gene), mcols(annoInfo)[idx,])

**Comment by Codezy99** [comment]
Yes, you are right. I will fix the bug now

**Comment by Codezy99** [comment]
Regarding the code you mention there, Kathi suggested to use the txDb instead of directly read the gff3 file. But in our miCLIP2 paper, we use the `level` information for the peak assignment. That is the reason why we read the gff3 file twice here. I will still discuss it with Kathi and find out the best solution ; )
